version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: estsban1102/backend-library:0.0.2
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data: